# Generated by Django 4.0.1 on 2022-01-18 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID'
                )),
                ('unit', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID'
                )),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID'
                )),
                ('absolute_value', models.IntegerField()),
                ('relative_value', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('counter', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to='app_meter.counter'
                )),
            ],
        ),
        migrations.AddField(
            model_name='counter',
            name='resource',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to='app_meter.resource'
            ),
        ),
    ]
