# Generated by Django 4.0.1 on 2022-01-20 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_meter', '0005_readings_delete_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readings',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='readings',
            name='meter',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='readings',
                to='app_meter.meter'
            ),
        ),
    ]
