# Generated by Django 4.0.1 on 2022-01-21 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_meter', '0007_alter_meter_name_alter_readings_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readings',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterUniqueTogether(
            name='readings',
            unique_together={('meter', 'date')},
        ),
    ]
