# Generated by Django 4.0.1 on 2022-01-25 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_meter', '0008_alter_readings_date_alter_readings_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='readings',
            options={'ordering': ('date',)},
        ),
    ]
