# Generated by Django 4.0.1 on 2022-01-19 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_meter', '0004_rename_counter_record_meter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Readings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('absolute_value', models.IntegerField()),
                ('relative_value', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='app_meter.meter')),
            ],
        ),
        migrations.DeleteModel(
            name='Record',
        ),
    ]
