# Generated by Django 4.0.1 on 2022-01-21 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_meter', '0006_alter_readings_date_alter_readings_meter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meter',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='readings',
            name='date',
            field=models.DateField(unique=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='name',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
